name: mcmessner Photography
favicon: null
layout_spectrum: 0.84899
typography_spectrum: 0.302030946360901
title: mcmessner photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8125
  lightness: 0.0625
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
